export type Challenge = {
  title: string;
  description: string;
  expectedOutput: string;
  tag: string;
};

export const challenges: Challenge[] = [
  {
    title: "Add Two Numbers",
    description: "Write a function to add 2 and 3.",
    expectedOutput: "5",
    tag: "easy",
  },
  {
    title: "Multiply Numbers",
    description: "Multiply 4 by 5.",
    expectedOutput: "20",
    tag: "easy",
  },
  {
    title: "Subtract Numbers",
    description: "Subtract 7 from 10.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Divide Numbers",
    description: "Divide 15 by 3.",
    expectedOutput: "5",
    tag: "easy",
  },
  {
    title: "String Length",
    description: "Find length of 'hello'.",
    expectedOutput: "5",
    tag: "easy",
  },
  {
    title: "First Character",
    description: "Get first char of 'test'.",
    expectedOutput: "t",
    tag: "easy",
  },
  {
    title: "Last Character",
    description: "Get last char of 'code'.",
    expectedOutput: "e",
    tag: "easy",
  },
  {
    title: "Concat Strings",
    description: "Concat 'hi' and 'there'.",
    expectedOutput: "hithere",
    tag: "easy",
  },
  {
    title: "Square Number",
    description: "Square 6.",
    expectedOutput: "36",
    tag: "easy",
  },
  {
    title: "Is Even",
    description: "Check if 8 is even.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Odd",
    description: "Check if 7 is odd.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Max of Two",
    description: "Find max of 5 and 9.",
    expectedOutput: "9",
    tag: "easy",
  },
  {
    title: "Min of Two",
    description: "Find min of 3 and 8.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Array Length",
    description: "Get length of [1,2,3].",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "First Element",
    description: "Get first element of [4,5,6].",
    expectedOutput: "4",
    tag: "easy",
  },
  {
    title: "Last Element",
    description: "Get last element of [7,8,9].",
    expectedOutput: "9",
    tag: "easy",
  },
  {
    title: "Sum Array",
    description: "Sum [1,2,3].",
    expectedOutput: "6",
    tag: "medium",
  },
  {
    title: "Average Array",
    description: "Average of [2,4,6].",
    expectedOutput: "4",
    tag: "medium",
  },
  {
    title: "Count Vowels",
    description: "Count vowels in 'hello'.",
    expectedOutput: "2",
    tag: "easy",
  },
  {
    title: "Count Consonants",
    description: "Count consonants in 'cat'.",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Reverse String",
    description: "Reverse 'dog'.",
    expectedOutput: "god",
    tag: "medium",
  },
  {
    title: "Is Palindrome",
    description: "Check if 'racecar' is palindrome.",
    expectedOutput: "true",
    tag: "medium",
  },
  {
    title: "Factorial",
    description: "Calculate factorial of 4.",
    expectedOutput: "24",
    tag: "medium",
  },
  {
    title: "Fibonacci Nth",
    description: "Get 5th Fibonacci number (start 0,1).",
    expectedOutput: "3",
    tag: "medium",
  },
  {
    title: "Power of Two",
    description: "Calculate 2 to power 3.",
    expectedOutput: "8",
    tag: "easy",
  },
  {
    title: "String to Upper",
    description: "Convert 'test' to uppercase.",
    expectedOutput: "TEST",
    tag: "easy",
  },
  {
    title: "String to Lower",
    description: "Convert 'CODE' to lowercase.",
    expectedOutput: "code",
    tag: "easy",
  },
  {
    title: "Trim String",
    description: "Trim '  hi  '.",
    expectedOutput: "hi",
    tag: "easy",
  },
  {
    title: "Includes Char",
    description: "Check if 'hello' includes 'e'.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Array Includes",
    description: "Check if [1,2,3] includes 2.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Join Array",
    description: "Join ['a','b','c'] with ''.",
    expectedOutput: "abc",
    tag: "easy",
  },
  {
    title: "Split String",
    description: "Split 'a,b,c' by ',' length.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Replace String",
    description: "Replace 'cat' with 'dog' in 'cat here'.",
    expectedOutput: "dog here",
    tag: "easy",
  },
  {
    title: "Starts With",
    description: "Check if 'hello' starts with 'he'.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Ends With",
    description: "Check if 'hello' ends with 'lo'.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Slice String",
    description: "Slice 'hello' from 1 to 3.",
    expectedOutput: "el",
    tag: "easy",
  },
  {
    title: "Array Push",
    description: "Push 4 to [1,2,3] and get length.",
    expectedOutput: "4",
    tag: "easy",
  },
  {
    title: "Array Pop",
    description: "Pop from [1,2,3].",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Array Shift",
    description: "Shift [1,2,3].",
    expectedOutput: "1",
    tag: "easy",
  },
  {
    title: "Array Unshift",
    description: "Unshift 0 to [1,2] and get length.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Object Keys",
    description: "Count keys in {a:1,b:2}.",
    expectedOutput: "2",
    tag: "easy",
  },
  {
    title: "Object Values",
    description: "Sum values in {a:1,b:3}.",
    expectedOutput: "4",
    tag: "medium",
  },
  {
    title: "Is Positive",
    description: "Check if 5 is positive.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Negative",
    description: "Check if -3 is negative.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Absolute Value",
    description: "Get absolute value of -7.",
    expectedOutput: "7",
    tag: "easy",
  },
  {
    title: "Round Number",
    description: "Round 3.7.",
    expectedOutput: "4",
    tag: "easy",
  },
  {
    title: "Floor Number",
    description: "Floor 5.9.",
    expectedOutput: "5",
    tag: "easy",
  },
  {
    title: "Ceil Number",
    description: "Ceil 2.1.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Max in Array",
    description: "Find max in [1,5,3].",
    expectedOutput: "5",
    tag: "medium",
  },
  {
    title: "Min in Array",
    description: "Find min in [4,2,7].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Count Char",
    description: "Count 'l' in 'hello'.",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Sum Evens",
    description: "Sum even numbers in [1,2,3,4].",
    expectedOutput: "6",
    tag: "medium",
  },
  {
    title: "Sum Odds",
    description: "Sum odd numbers in [1,2,3,4].",
    expectedOutput: "4",
    tag: "medium",
  },
  {
    title: "String Repeat",
    description: "Repeat 'ha' 3 times.",
    expectedOutput: "hahahaha",
    tag: "easy",
  },
  {
    title: "Is Prime",
    description: "Check if 7 is prime.",
    expectedOutput: "true",
    tag: "medium",
  },
  {
    title: "GCD",
    description: "Find GCD of 48 and 18.",
    expectedOutput: "6",
    tag: "medium",
  },
  {
    title: "LCM",
    description: "Find LCM of 6 and 8.",
    expectedOutput: "24",
    tag: "medium",
  },
  {
    title: "Modulo",
    description: "Find 10 mod 3.",
    expectedOutput: "1",
    tag: "easy",
  },
  {
    title: "Cube Number",
    description: "Cube 3.",
    expectedOutput: "27",
    tag: "easy",
  },
  {
    title: "Double Array",
    description: "Double each in [1,2,3] and sum.",
    expectedOutput: "12",
    tag: "medium",
  },
  {
    title: "String Index",
    description: "Find index of 'l' in 'hello'.",
    expectedOutput: "2",
    tag: "easy",
  },
  {
    title: "Last Index",
    description: "Find last index of 'l' in 'hello'.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "Array Index",
    description: "Find index of 2 in [1,2,3].",
    expectedOutput: "1",
    tag: "easy",
  },
  {
    title: "Is Zero",
    description: "Check if 0 is zero.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "String Pad Start",
    description: "Pad '7' with '0' to length 3.",
    expectedOutput: "007",
    tag: "easy",
  },
  {
    title: "String Pad End",
    description: "Pad 'hi' with '!' to length 4.",
    expectedOutput: "hi!!",
    tag: "easy",
  },
  {
    title: "Toggle Case",
    description: "Toggle case of 'Hi'.",
    expectedOutput: "hI",
    tag: "medium",
  },
  {
    title: "Count Words",
    description: "Count words in 'hi there'.",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "First Word",
    description: "Get first word of 'hello world'.",
    expectedOutput: "hello",
    tag: "easy",
  },
  {
    title: "Last Word",
    description: "Get last word of 'hi there now'.",
    expectedOutput: "now",
    tag: "easy",
  },
  {
    title: "Array Reverse",
    description: "Reverse [1,2,3] and get first.",
    expectedOutput: "3",
    tag: "medium",
  },
  {
    title: "Odd Count",
    description: "Count odds in [1,2,3,4,5].",
    expectedOutput: "3",
    tag: "medium",
  },
  {
    title: "Even Count",
    description: "Count evens in [1,2,3,4].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Positive Count",
    description: "Count positives in [1,-2,3].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Negative Count",
    description: "Count negatives in [-1,2,-3].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Zero Count",
    description: "Count zeros in [0,1,0,2].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Sum Digits",
    description: "Sum digits of 123.",
    expectedOutput: "6",
    tag: "medium",
  },
  {
    title: "Product Digits",
    description: "Multiply digits of 234.",
    expectedOutput: "24",
    tag: "medium",
  },
  {
    title: "Is Alphabet",
    description: "Check if 'a' is alphabet.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Digit",
    description: "Check if '5' is digit.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Char Code",
    description: "Get char code of 'A'.",
    expectedOutput: "65",
    tag: "easy",
  },
  {
    title: "From Char Code",
    description: "Get char from code 97.",
    expectedOutput: "a",
    tag: "easy",
  },
  {
    title: "String Includes Word",
    description: "Check if 'hello world' includes 'world'.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Array Every Even",
    description: "Check if all in [2,4,6] are even.",
    expectedOutput: "true",
    tag: "medium",
  },
  {
    title: "Array Some Odd",
    description: "Check if some in [2,3,4] are odd.",
    expectedOutput: "true",
    tag: "medium",
  },
  {
    title: "Array Filter Positive",
    description: "Count positives in [-1,2,3].",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Array Reduce Sum",
    description: "Reduce [1,2,3] to sum.",
    expectedOutput: "6",
    tag: "medium",
  },
  {
    title: "Object Has Key",
    description: "Check if {a:1} has key 'a'.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "String Match Count",
    description: "Count 'l' matches in 'hello'.",
    expectedOutput: "2",
    tag: "medium",
  },
  {
    title: "Number to String",
    description: "Convert 123 to string length.",
    expectedOutput: "3",
    tag: "easy",
  },
  {
    title: "String to Number",
    description: "Convert '45' to number.",
    expectedOutput: "45",
    tag: "easy",
  },
  {
    title: "Boolean to String",
    description: "Convert true to string.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Greater",
    description: "Check if 5 > 3.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Less",
    description: "Check if 2 < 4.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Is Equal",
    description: "Check if 5 equals 5.",
    expectedOutput: "true",
    tag: "easy",
  },
  {
    title: "Clamp Number",
    description: "Clamp 15 between 0 and 10.",
    expectedOutput: "10",
    tag: "medium",
  },
  {
    title: "Sign of Number",
    description: "Get sign of -5.",
    expectedOutput: "-1",
    tag: "easy",
  },
  {
    title: "Digits Count",
    description: "Count digits in 1234.",
    expectedOutput: "4",
    tag: "medium",
  },
  {
    title: "Reverse Number",
    description: "Reverse digits of 123.",
    expectedOutput: "321",
    tag: "medium",
  },
];
